### ISSUE TITLE
Inconsistent results with nullable property

### ISSUE THREAD

**Issue by eigan** [CuyZ/Valinor#114]
When the source is empty, is the mapper not able to set `null` to nullable property.

### Reproduction
```php
use CuyZ\Valinor\Mapper\MappingError;

require "vendor/autoload.php";

final class Foo
{
    public string|null $note;
}

final class Bar
{
    public string|null $note;

    public string $title;
}

try {
    $foo = (new \CuyZ\Valinor\MapperBuilder())
        ->mapper()
        ->map(Foo::class, []);
} catch (MappingError $e) {
    // Foo: Cannot cast value of type `array` to `string`.
    // Caused by ClassNodeBuilder::transformSource()
    // $source is [] and since the property $note does not exist in $source
    // will it return $source = [$name => $source];

    foreach($e->node()->children() as $child) {
        foreach($child->messages() as $message) {
            echo "Foo: " . $message . "\n";
        }
    }
}

// No issues:
$bar = (new \CuyZ\Valinor\MapperBuilder())
    ->mapper()
    ->map(Bar::class, ['title' => 'Foo']);

$bar->note === null; // true
```

### Expected behavior
`Foo::$note` should be assigned `null` as value to be consistent with example `Bar`, but see my other issue here: #113.

**Comment by eigan** [comment]
Introducing a second nullable will make it possible to map.

```php
final class Foo
{
    public string|null $note;
    public string|null $note2;
}


$foo = (new \CuyZ\Valinor\MapperBuilder())
    ->mapper()
    ->map(Foo::class, []);

$foo->note === null; // true

```

**Comment by eigan** [comment]
```php
final class Foo
{
    public Bar|null $bar;
}

class Bar {
    public string|null $title;
    public string|null $title2;
}

$foo = (new \CuyZ\Valinor\MapperBuilder())
    ->mapper()
    ->map(Foo::class, []);

$foo->bar instanceof Bar; // true
```
Introducing a new property yields different result. `Foo::$bar` is no longer a `Bar`.
```php
final class Foo
{
    public $title; // New property

    public Bar|null $bar;
}

class Bar {
    public string|null $title;
    public string|null $title2;
}

$foo = (new \CuyZ\Valinor\MapperBuilder())
    ->mapper()
    ->map(Foo::class, []);

$foo->bar instanceof Bar; // false
```

**Comment by romm** [comment]
Thanks for the excellent reproduction steps, I will definitely take a look at it.

Also, looks like it's bound to #34.

**Comment by romm** [comment]
Hi @eigan, thanks again for the report, that helped a lot for #159. Could you try on your side to see if this leads to expected behaviors?

**Comment by eigan** [comment]
@romm Thanks! :) 

Not sure if this fits here, but anyway, some testing:

```php
<?php
require "vendor/autoload.php";

use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\Mapper\Tree\Node;

require "vendor/autoload.php";

final class Foo
{
    public string $note = "ok";
    public Foo $foo;
}

try {
    (new \CuyZ\Valinor\MapperBuilder())
        ->mapper()
        ->map(Foo::class, []);
} catch (MappingError $e) {
    print_node($e->node());
}

function print_node(Node $node): void
{
    foreach ($node->messages() as $message) {
        echo $node->path() . ": " .$message . "\n";
    }

    foreach ($node->children() as $child) {
        print_node($child);
    }
}


```
## Result
```
foo: Cannot be empty and must be filled with a value matching type `?`.
``` 
## Expected
```
foo: Cannot be empty and must be filled with a value matching type `array{note?: string, foo: ?}|null`.
```
Nested type might be a bit tricky to render any further.. :)

**Comment by eigan** [comment]
```php
<?php

require "vendor/autoload.php";

final class Foo
{
    public ?Foo $foo;
}

(new \CuyZ\Valinor\MapperBuilder())
    ->mapper()
    ->map(Foo::class, [
        'bar' => 'String'
    ]);
```

## Result
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in src/Mapper/Tree/Builder/CasterProxyNodeBuilder.php on line 30
```

Changing type to `Foo` triggeres the same error from `src/Mapper/Tree/Builder/ClassNodeBuilder.php on line 91`

**Comment by eigan** [comment]
```php
<?php

require "vendor/autoload.php";

use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\Mapper\Tree\Node;

final class Foo
{
    public ?string $bar = null;
}

try {
    (new \CuyZ\Valinor\MapperBuilder())
        ->mapper()
        ->map(Foo::class, []);
} catch (MappingError $e) {
    print_node($e->node());
}

function print_node(Node $node): void
{
    foreach ($node->messages() as $message) {
        echo $node->path() . ": " .$message . "\n";
    }

    foreach ($node->children() as $child) {
        print_node($child);
    }
}

``` 

## Result
```
bar: Cannot be empty and must be filled with a value matching type `string|null`.
```

## Expected
No error. $bar is nullable and has default value of null. There is no error when the default value is a string, so it is partially implemented.

**Comment by romm** [comment]
Hi @eigan, really good catch! Should be fixed with my last commit in #159, can you confirm?

**Comment by eigan** [comment]
- Issue with nullable and default null seems to be fixed 👍🏻 
- Memory issue still an issue, though seems to be an issue in master too.

Seems like you have solved all my points in this issue now 👏🏻 

------

Recursive issue: Take a look at the following example. When sending a nested value, the error is reported as expected _(type of Foo is exposed)_. So it seems to be sort-of implemented. But, I can agree that this is a non-blocking issue 🙂 

```php
require "vendor/autoload.php";

use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\Mapper\Tree\Node;

final class Foo
{
    public string $note = "hello";
    public ?Foo $foo;
}

try {
    (new \CuyZ\Valinor\MapperBuilder())
        ->mapper()
        ->map(Foo::class, [
            'foo' => [
                'foo' => 'ok'
            ]
        ]);
} catch (MappingError $e) {
    print_node($e->node());
}

function print_node(Node $node): void
{
    foreach ($node->messages() as $message) {
        echo $node->path() . ": " .$message . "\n";
    }

    foreach ($node->children() as $child) {
        print_node($child);
    }
}
```

## Result
```
foo.foo: Value 'ok' does not match type `array{note?: string, foo: ?}`.
```

**Comment by romm** [comment]
Fixed with #159.
